[#1] properties 파일 추가 및 build.gradle 수정
team-i-dle/idle-api pull request #1
Opened 2022-07-13 06:57 UTC by jylee1017

application.properties 파일 및 소셜 로그인 적용을 위한 application-oauth.properties 파일(예시용) 추가 
spring boot oauth2 client, spring session jdbc, spring security test 라이브러리 추가

2022-07-14 14:45 UTC, ghkvud2 requested changes
properties를 yml로 바꿔보는건 어떨까요?
테스트용으로 Request Change를 날려봅니다~ㅎㅎ

2022-07-15 02:43 UTC, jylee1017 commented
넵 yml로 바꿔서 다시 PR 날리겠습니다~ 혹시 이렇게 변경사항 merge 안하고 다시 PR 요청하는 경우는 현재 PR close 시키고 PR을 다시 날리면 되는 걸까요?

2022-07-15 03:17 UTC, ghkvud2 commented
저도 처음이라.....(머쓱)ㅋㅋㅋ
찾아보신대로 닫고나서 다시하며니되지않을까요?

2022-07-15 03:19 UTC, ghkvud2 commented
> 넵 yml로 바꿔서 다시 PR 날리겠습니다~ 혹시 이렇게 변경사항 merge 안하고 다시 PR 요청하는 경우는 현재 PR close 시키고 PR을 다시 날리면 되는 걸까요? 검색통해 찾아보니 close 후 다시 PR 요청식으로 하는 거 같긴한데 혹시 몰라 여쭤봅니다!

저도 처음이라.....(머쓱)ㅋㅋㅋ
찾아보신대로 닫고나서 다시하며니되지않을까요?

2022-07-19 04:54 UTC, closed without merging

2022-07-19 04:54 UTC, ghkvud2 commented
YAML 파일로 수정 요청